dataset: "matteroffact_all"

model: "qwen2.5-72b-instruct"
api_url: "https://api.avalai.ir/v1/chat/completions"

labels:
  - Supported
  - Refuted

prompt_methods:
  - naive
  - strong_baseline_short
  - cognitive_bias_aware

temporal_split: "2024-09-01"
date_format: "%Y-%m-%d"

rate_limit:
  max_retries: 5
  initial_retry_delay: 0.5
  sleep_between_calls: 0.1

sampling:
  max_samples: 1
  balanced: true
  seed: 42

display_every_n: 10

output_root: "results"
api_key_env: "aa-7WCmv4uyk7z1VIUl3QjoNCDAOkQBpvNKbSSjOsbLwJvcfakK"

datasets_config: "datasets.yaml"