# -*- coding: utf-8 -*-
"""run_fact_check_inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yhgHkZa7t_JWjuayU7lr7viGCVO4w6dj

# Production-Level Fact-Checking Model Inference

This notebook provides a unified pipeline for running fact-checking inference across multiple datasets:
- **ClaimReview Plus** (HuggingFace)
- **FACTors** (CSV format)
- **AVeriTeC FEVER** (Train/Dev/Test JSON format)

## Features
- Configurable dataset selection and model parameters
- Temporal split analysis (seen vs. unseen data)
- Statistical significance testing
- Comprehensive error handling and logging
- Production-ready code structure

---

## 1. Setup & Installation

Install required packages and import dependencies.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# # Install required packages (use %pip for proper notebook environment handling)
# %pip install -q requests tqdm datasets pandas scipy

# Standard library imports
import os
import re
import json
import logging
import time
import random
from pathlib import Path
from typing import Dict, List, Optional, Any, Tuple
from datetime import datetime
from collections import defaultdict

# Third-party imports
import requests
import pandas as pd
from tqdm.notebook import tqdm
from datasets import load_dataset
from scipy import stats

# Set HuggingFace API token

os.environ["HF_TOKEN"] = "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"
print("✓ All libraries loaded successfully")

"""## 2. Configuration Parameters

Configure all hyperparameters, dataset selection, and model settings.
"""

# ==================== CONFIGURATION ====================

# Dataset Selection
# Options: "claimreview_plus", "factors", "fever_train", "fever_dev", "fever_test_2023_2024", "fever_test_2025"
DATASET_NAME = "factors"

# Model Configuration
# MODEL_NAME = "anthropic.claude-3-5-sonnet-20241022-v2:0"
MODEL_NAME = "cf.llama-3.1-70b-instruct"
AVALAI_API_KEY = os.environ.get("AVALAI_API_KEY", "aa-7WCmv4uyk7z1VIUl3QjoNCDAOkQBpvNKbSSjOsbLwJvcfakK")
AVALAI_CHAT_URL = "https://api.avalai.ir/v1/chat/completions"

# Label Configuration (Customize based on your task)
CANONICAL_LABELS = [
    'false',
    'misleading',
    'partially true',
    'true',
]

# API Rate Limiting
MAX_RETRIES = 5
INITIAL_RETRY_DELAY = 0.5  # seconds
SLEEP_BETWEEN_CALLS = 0.1 # seconds (increased for rate limit safety)

# Temporal Split Configuration
TEMPORAL_SPLIT_DATE = "2024-04-01"  # Split date for seen/unseen analysis
DATE_FORMAT = "%d-%m-%Y"  # Format used in datasets

# Sampling Configuration (set to None to process all data)
MAX_SAMPLES = None  # or set to a number like 100 for testing

# Balanced Sampling for Large Datasets (e.g., FACTors)
# When enabled, samples seen data to match unseen data size for faster runs
BALANCED_SAMPLING = True  # Set to True to enable balanced sampling
SAMPLING_SEED = 42  # Random seed for reproducibility (change for different samples)

# Display Configuration
DISPLAY_EVERY_N = 10  # Show progress every N claims

# Output Directory
OUTPUT_DIR = Path("results") / MODEL_NAME.replace(":", "_").replace(".", "_") / DATASET_NAME
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print(f"✓ Configuration loaded")
print(f"  Dataset: {DATASET_NAME}")
print(f"  Model: {MODEL_NAME}")
print(f"  Output Directory: {OUTPUT_DIR}")
print(f"  Labels: {CANONICAL_LABELS}")
print(f"  Balanced Sampling: {BALANCED_SAMPLING}" + (f" (seed={SAMPLING_SEED})" if BALANCED_SAMPLING else ""))

"""## 3. Utility Functions

Core utility functions for logging, label normalization, and API interaction.
"""

def setup_logger(log_file: Path) -> logging.Logger:
    """
    Configure and return a logger with file and console handlers.

    Args:
        log_file: Path to the log file

    Returns:
        Configured logger instance
    """
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.INFO)
    logger.handlers = []

    # File handler
    file_handler = logging.FileHandler(log_file, mode='w', encoding='utf-8')
    file_handler.setLevel(logging.INFO)
    file_formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    file_handler.setFormatter(file_formatter)
    logger.addHandler(file_handler)

    # Console handler
    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.WARNING)
    console_formatter = logging.Formatter('%(levelname)s - %(message)s')
    console_handler.setFormatter(console_formatter)
    logger.addHandler(console_handler)

    return logger


def normalize_label(label: str, canonical_labels: List[str]) -> Optional[str]:
    """
    Normalize a label to match canonical format.

    Args:
        label: Input label to normalize
        canonical_labels: List of valid canonical labels

    Returns:
        Normalized label or None if unverifiable/invalid
    """
    if not label or not isinstance(label, str):
        return None

    label_lower = label.lower().strip()

    # Direct match (case-insensitive) - CHECK THIS FIRST
    for canonical in canonical_labels:
        if label_lower == canonical.lower():
            return canonical

    # Partial match - CHECK THIS SECOND
    for canonical in canonical_labels:
        if canonical.lower() in label_lower or label_lower in canonical.lower():
            return canonical

    # Check for unverifiable/not enough info cases ONLY if not in canonical labels
    unverifiable_keywords = ["not enough", "unverifiable", "inconclusive", "unclear"]
    if any(keyword in label_lower for keyword in unverifiable_keywords):
        return None

    # Handle common mappings
    label_mappings = {
        "true": "Supported",
        "false": "Refuted",
        "mostly true": "Supported",
        "mostly false": "Refuted",
        "half true": "Partially true",
        "mixture": "Misleading",
        "outdated": "Misleading",
        "cherry picking": "Misleading",
        "correct attribution": "Supported",
        "incorrect attribution": "Refuted",
    }

    for key, value in label_mappings.items():
        if key in label_lower and value in canonical_labels:
            return value

    return None


def ask_model(claim: str, date: str, model_name: str, api_key: str,
              api_url: str, labels: List[str], logger: logging.Logger,
              max_retries: int = MAX_RETRIES) -> Optional[str]:
    """
    Query the language model for fact-checking prediction with retry logic.

    Args:
        claim: Claim text to fact-check
        date: Claim date
        model_name: Name of the model to use
        api_key: API authentication key
        api_url: API endpoint URL
        labels: List of valid labels
        logger: Logger instance
        max_retries: Maximum number of retry attempts

    Returns:
        Predicted label or None if failed
    """
    prompt = f"""You are a fact-checking expert. Analyze the following claim and classify it into one of these categories: {', '.join(labels)}.

Claim: {claim}
Date: {date}

Respond ONLY with a JSON object in this exact format:
{{"label": "your_classification"}}

Choose the label that best represents the claim's veracity."""

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": model_name,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.1,
        "max_tokens": 50
    }

    logger.info(f"Asking model: {model_name}")
    logger.info(f"Claim: {claim[:150]}...")

    retry_delay = INITIAL_RETRY_DELAY

    for attempt in range(max_retries + 1):
        try:
            response = requests.post(api_url, json=payload, headers=headers, timeout=30)
            logger.info(f"API Response Status: {response.status_code}")

            if response.status_code == 429:
                if attempt < max_retries:
                    logger.info(f"Retry attempt {attempt + 1}/{max_retries} after {retry_delay}s delay...")
                    time.sleep(retry_delay)
                    retry_delay *= 2
                    continue
                else:
                    logger.error("Max retries reached for rate limit")
                    return None

            if response.status_code == 200:
                result = response.json()
                content = result.get("choices", [{}])[0].get("message", {}).get("content", "")
                logger.info(f"Raw model response: {content}")

                # Extract JSON from response
                json_match = re.search(r'\{.*?\}', content, re.DOTALL)
                if json_match:
                    parsed = json.loads(json_match.group(0))
                    raw_label = parsed.get("label", "")
                    normalized = normalize_label(raw_label, labels)
                    logger.info(f"Extracted label: {raw_label} -> Normalized: {normalized}")
                    return normalized

                logger.warning(f"Could not parse JSON from response: {content}")
                return None

            logger.error(f"API error: {response.status_code} - {response.text}")
            return None

        except (requests.exceptions.Timeout, requests.exceptions.ConnectionError) as e:
            if attempt < max_retries:
                logger.warning(f"Network error: {e}. Retrying...")
                time.sleep(retry_delay)
                retry_delay *= 2
                continue
            logger.error(f"Network error after {max_retries} retries: {e}")
            return None

        except Exception as e:
            logger.error(f"Unexpected error: {e}")
            return None

    return None

print("✓ Utility functions defined")

"""## 4. Dataset Loaders

Functions to load and standardize different dataset formats.
"""

def load_claimreview_plus() -> List[Dict[str, Any]]:
    """
    Load ClaimReview Plus dataset from HuggingFace.

    Returns:
        List of standardized claim dictionaries
    """
    print("Loading ClaimReview Plus from HuggingFace...")
    dataset = load_dataset("MAI-Lab/ClaimReview2024plus", split="test", token=os.environ.get("HF_TOKEN"))

    claims = []
    for idx, item in enumerate(dataset):
        claims.append({
            "claim_id": idx,
            "claim": item.get("claim", ""),
            "claim_date": item.get("claimDate", ""),
            "label": item.get("rating", ""),
            "speaker": item.get("claimant", None),
            "source": "claimreview_plus"
        })

    print(f"✓ Loaded {len(claims)} claims from ClaimReview Plus")
    return claims


def load_factors() -> List[Dict[str, Any]]:
    """
    Load FACTors dataset from CSV file.
    Filters out claims with 'other' and 'unverifiable' labels.

    Returns:
        List of standardized claim dictionaries
    """
    csv_path = Path("Datasets/FACTor/FACTors.csv")
    print(f"Loading FACTors from {csv_path}...")

    df = pd.read_csv(csv_path)

    # Filter out 'other' and 'unverifiable' labels
    excluded_labels = ['other', 'unverifiable']
    original_count = len(df)
    df = df[~df['normalised_rating'].isin(excluded_labels)]
    filtered_count = original_count - len(df)

    print(f"  Filtered out {filtered_count} claims with labels: {excluded_labels}")

    claims = []
    for _, row in df.iterrows():
        # Parse date from ISO format to dd-mm-yyyy
        try:
            date_obj = datetime.fromisoformat(str(row['date_published']).replace('T00:00:00', ''))
            formatted_date = date_obj.strftime(DATE_FORMAT)
        except:
            formatted_date = ""

        claims.append({
            "claim_id": row['claim_id'],
            "claim": row['claim'],
            "claim_date": formatted_date,
            "label": str(row['normalised_rating']).capitalize() if pd.notna(row['normalised_rating']) else "",
            "speaker": row.get('author', None),
            "source": "factors"
        })

    print(f"✓ Loaded {len(claims)} claims from FACTors (after filtering)")
    return claims


def load_fever_json(file_path: Path, is_test: bool = False) -> List[Dict[str, Any]]:
    """
    Load FEVER dataset from JSON file.

    Args:
        file_path: Path to the JSON file
        is_test: Whether this is test data (no labels)

    Returns:
        List of standardized claim dictionaries
    """
    print(f"Loading FEVER dataset from {file_path}...")

    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    claims = []
    for item in data:
        claim_dict = {
            "claim_id": item.get("claim_id", len(claims)),
            "claim": item["claim"],
            "claim_date": item.get("claim_date", ""),
            "speaker": item.get("speaker", None),
            "source": file_path.stem
        }

        # Add label only if not test data
        if not is_test:
            claim_dict["label"] = item.get("label", "")

        # Preserve original fields for test data
        if is_test:
            claim_dict["original_data"] = item

        claims.append(claim_dict)

    print(f"✓ Loaded {len(claims)} claims from {file_path.name}")
    return claims


def load_dataset_by_name(dataset_name: str) -> Tuple[List[Dict[str, Any]], bool]:
    """
    Load dataset based on configuration name.

    Args:
        dataset_name: Name of the dataset to load

    Returns:
        Tuple of (claims list, is_test_data boolean)
    """
    base_path = Path("Datasets")

    if dataset_name == "claimreview_plus":
        return load_claimreview_plus(), False

    elif dataset_name == "factors":
        return load_factors(), False

    elif dataset_name == "fever_train":
        return load_fever_json(base_path / "AVeriTeC_FEVER" / "train.json", is_test=False), False

    elif dataset_name == "fever_dev":
        return load_fever_json(base_path / "AVeriTeC_FEVER" / "data_dev.json", is_test=False), False

    elif dataset_name == "fever_test_2023_2024":
        return load_fever_json(base_path / "AVeriTeC_FEVER" / "test_2023_2024.json", is_test=True), True

    elif dataset_name == "fever_test_2025":
        return load_fever_json(base_path / "AVeriTeC_FEVER" / "test_2025.json", is_test=True), True

    else:
        raise ValueError(f"Unknown dataset: {dataset_name}")

print("✓ Dataset loader functions defined")

"""## 5. Temporal Split & Processing Functions

Functions for splitting data by date and processing claims.
"""

def split_by_date(claims: List[Dict[str, Any]], split_date: str) -> Tuple[List[Dict], List[Dict]]:
    """
    Split claims into seen (before split date) and unseen (after split date).

    Args:
        claims: List of claim dictionaries
        split_date: Split date in YYYY-MM-DD format

    Returns:
        Tuple of (seen_claims, unseen_claims)
    """
    split_dt = datetime.strptime(split_date, "%Y-%m-%d")
    seen = []
    unseen = []
    no_date = []

    for claim in claims:
        date_str = claim.get("claim_date", "")
        if not date_str:
            no_date.append(claim)
            continue

        try:
            # Try parsing with the configured format
            claim_dt = datetime.strptime(date_str, DATE_FORMAT)
        except:
            try:
                # Try ISO format
                claim_dt = datetime.fromisoformat(date_str.replace('T00:00:00', ''))
            except:
                no_date.append(claim)
                continue

        if claim_dt < split_dt:
            seen.append(claim)
        else:
            unseen.append(claim)

    print(f"✓ Split complete: {len(seen)} seen, {len(unseen)} unseen, {len(no_date)} without date")

    # Add no_date claims to seen by default
    seen.extend(no_date)

    return seen, unseen


def process_claims(claims: List[Dict[str, Any]], is_test: bool, logger: logging.Logger) -> List[Dict[str, Any]]:
    """
    Process claims through the model and collect predictions.

    Args:
        claims: List of claim dictionaries
        is_test: Whether this is test data (no ground truth labels)
        logger: Logger instance

    Returns:
        List of claims with predictions added
    """
    results = []
    successful = 0
    failed = 0
    correct = 0
    incorrect = 0

    # Apply sampling if configured
    if MAX_SAMPLES and len(claims) > MAX_SAMPLES:
        claims = claims[:MAX_SAMPLES]
        logger.info(f"Processing {MAX_SAMPLES} samples (limited for testing)")

    logger.info(f"Processing {len(claims)} claims...")

    # Create progress bar with different formats for test vs labeled data
    if is_test:
        pbar = tqdm(claims, desc="Processing claims",
                    bar_format='{l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}, {rate_fmt}] Success: {postfix[0]}, Failed: {postfix[1]}',
                    postfix=[0, 0])
    else:
        pbar = tqdm(claims, desc="Processing claims",
                    bar_format='{l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}, {rate_fmt}] Correct: {postfix[0]}, Incorrect: {postfix[1]}, Failed: {postfix[2]}',
                    postfix=[0, 0, 0])

    for idx, claim_dict in enumerate(pbar):
        claim = claim_dict["claim"]
        date = claim_dict.get("claim_date", "")
        claim_id = claim_dict.get("claim_id", idx)

        logger.info("=" * 80)
        logger.info(f"Processing claim #{idx} (ID: {claim_id})")
        logger.info(f"Claim: {claim[:150]}...")
        logger.info(f"Date: {date}")

        # Get model prediction
        prediction = ask_model(
            claim=claim,
            date=date,
            model_name=MODEL_NAME,
            api_key=AVALAI_API_KEY,
            api_url=AVALAI_CHAT_URL,
            labels=CANONICAL_LABELS,
            logger=logger
        )

        # Add prediction to result
        result = claim_dict.copy()

        if prediction:
            result["prediction"] = prediction
            result["prediction_error"] = None
            logger.info(f"Prediction: {prediction}")
            successful += 1

            # For labeled data, check if prediction is correct
            if not is_test and claim_dict.get("label"):
                true_label = normalize_label(claim_dict["label"], CANONICAL_LABELS)
                if true_label and prediction == true_label:
                    correct += 1
                    logger.info(f"✓ Correct prediction")
                elif true_label:
                    incorrect += 1
                    logger.info(f"✗ Incorrect prediction (True: {true_label}, Pred: {prediction})")

            # Display progress every N claims
            if (idx + 1) % DISPLAY_EVERY_N == 0:
                print(f"\n[Claim #{idx + 1}] {claim[:100]}...")
                print(f"  → Prediction: {prediction}")
                if not is_test and claim_dict.get("label"):
                    true_label = normalize_label(claim_dict["label"], CANONICAL_LABELS)
                    if true_label:
                        print(f"  → Ground Truth: {true_label}")
                        print(f"  → {'✓ Correct' if prediction == true_label else '✗ Incorrect'}")
        else:
            result["prediction"] = None
            result["prediction_error"] = "Failed to get valid prediction"
            logger.warning("Failed to get valid prediction")
            failed += 1

        results.append(result)

        # Update progress bar with appropriate metrics
        if is_test:
            pbar.postfix = [successful, failed]
            pbar.set_description(f"Processing claims [✓{successful} ✗{failed}]")
        else:
            pbar.postfix = [correct, incorrect, failed]
            pbar.set_description(f"Processing claims [✓{correct} ✗{incorrect} Failed:{failed}]")

        # Rate limiting
        time.sleep(SLEEP_BETWEEN_CALLS)

    logger.info("=" * 80)
    if is_test:
        logger.info(f"Processing complete: {successful} successful, {failed} failed")
    else:
        logger.info(f"Processing complete: {successful} predictions ({correct} correct, {incorrect} incorrect), {failed} failed")

    return results

print("✓ Processing functions defined")

"""## 6. Evaluation & Statistical Analysis

Functions for computing metrics and statistical significance tests.
"""

def calculate_metrics(results: List[Dict[str, Any]], logger: logging.Logger) -> Dict[str, Any]:
    """
    Calculate performance metrics for predictions with ground truth.

    Args:
        results: List of results with predictions and labels
        logger: Logger instance

    Returns:
        Dictionary of metrics
    """
    # Filter valid predictions
    valid_results = [
        r for r in results
        if r.get("prediction") and r.get("label") and
        normalize_label(r["label"], CANONICAL_LABELS)
    ]

    if not valid_results:
        logger.warning("No valid results for metric calculation")
        return {"error": "No valid results"}

    # Normalize labels and collect predictions
    correct = 0
    total = len(valid_results)
    label_counts = defaultdict(int)
    confusion = defaultdict(lambda: defaultdict(int))

    for result in valid_results:
        true_label = normalize_label(result["label"], CANONICAL_LABELS)
        pred_label = result["prediction"]

        label_counts[true_label] += 1
        confusion[true_label][pred_label] += 1

        if true_label == pred_label:
            correct += 1

    accuracy = correct / total if total > 0 else 0.0

    # Calculate per-label metrics
    per_label_metrics = {}
    for label in CANONICAL_LABELS:
        if label_counts[label] == 0:
            continue

        tp = confusion[label][label]
        fn = label_counts[label] - tp
        fp = sum(confusion[other][label] for other in CANONICAL_LABELS if other != label)

        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0

        per_label_metrics[label] = {
            "precision": round(precision, 4),
            "recall": round(recall, 4),
            "f1": round(f1, 4),
            "support": label_counts[label]
        }

    # Calculate macro averages
    precisions = [m["precision"] for m in per_label_metrics.values()]
    recalls = [m["recall"] for m in per_label_metrics.values()]
    f1s = [m["f1"] for m in per_label_metrics.values()]

    metrics = {
        "accuracy": round(accuracy, 4),
        "macro_precision": round(sum(precisions) / len(precisions), 4) if precisions else 0.0,
        "macro_recall": round(sum(recalls) / len(recalls), 4) if recalls else 0.0,
        "macro_f1": round(sum(f1s) / len(f1s), 4) if f1s else 0.0,
        "total_samples": total,
        "correct_predictions": correct,
        "per_label_metrics": per_label_metrics
    }

    logger.info(f"Metrics: Accuracy={metrics['accuracy']:.4f}, Macro-F1={metrics['macro_f1']:.4f}")

    return metrics


def compare_seen_unseen(seen_results: List[Dict], unseen_results: List[Dict],
                        logger: logging.Logger) -> Dict[str, Any]:
    """
    Compare performance on seen vs unseen data with statistical testing.

    Args:
        seen_results: Results from seen data
        unseen_results: Results from unseen data
        logger: Logger instance

    Returns:
        Dictionary with comparison statistics
    """
    logger.info("=" * 80)
    logger.info("Comparing seen vs unseen performance...")

    # Calculate metrics for each split
    seen_metrics = calculate_metrics(seen_results, logger)
    unseen_metrics = calculate_metrics(unseen_results, logger)

    # Extract accuracies for statistical test
    seen_correct = [1 if r.get("prediction") == normalize_label(r.get("label", ""), CANONICAL_LABELS) else 0
                    for r in seen_results
                    if r.get("prediction") and r.get("label")]

    unseen_correct = [1 if r.get("prediction") == normalize_label(r.get("label", ""), CANONICAL_LABELS) else 0
                      for r in unseen_results
                      if r.get("prediction") and r.get("label")]

    # Perform statistical significance test (two-sample t-test)
    if len(seen_correct) > 1 and len(unseen_correct) > 1:
        t_stat, p_value = stats.ttest_ind(seen_correct, unseen_correct)

        # Also perform chi-square test
        seen_success = sum(seen_correct)
        seen_total = len(seen_correct)
        unseen_success = sum(unseen_correct)
        unseen_total = len(unseen_correct)

        contingency_table = [
            [seen_success, seen_total - seen_success],
            [unseen_success, unseen_total - unseen_success]
        ]
        chi2, chi_p_value, dof, expected = stats.chi2_contingency(contingency_table)

        comparison = {
            "seen_metrics": seen_metrics,
            "unseen_metrics": unseen_metrics,
            "statistical_tests": {
                "t_test": {
                    "t_statistic": round(t_stat, 4),
                    "p_value": round(p_value, 4),
                    "significant_at_0.05": p_value < 0.05,
                    "interpretation": "Significant difference" if p_value < 0.05 else "No significant difference"
                },
                "chi_square_test": {
                    "chi2_statistic": round(chi2, 4),
                    "p_value": round(chi_p_value, 4),
                    "degrees_of_freedom": dof,
                    "significant_at_0.05": chi_p_value < 0.05,
                    "interpretation": "Significant difference" if chi_p_value < 0.05 else "No significant difference"
                }
            },
            "accuracy_difference": round(unseen_metrics["accuracy"] - seen_metrics["accuracy"], 4)
        }

        logger.info(f"Seen accuracy: {seen_metrics['accuracy']:.4f}")
        logger.info(f"Unseen accuracy: {unseen_metrics['accuracy']:.4f}")
        logger.info(f"Difference: {comparison['accuracy_difference']:.4f}")
        logger.info(f"T-test p-value: {p_value:.4f} ({'significant' if p_value < 0.05 else 'not significant'})")
        logger.info(f"Chi-square p-value: {chi_p_value:.4f} ({'significant' if chi_p_value < 0.05 else 'not significant'})")
    else:
        comparison = {
            "seen_metrics": seen_metrics,
            "unseen_metrics": unseen_metrics,
            "statistical_tests": "Insufficient data for statistical testing",
            "accuracy_difference": round(unseen_metrics.get("accuracy", 0) - seen_metrics.get("accuracy", 0), 4)
        }
        logger.warning("Insufficient data for statistical testing")

    return comparison

print("✓ Evaluation functions defined")

"""## 7. Output & Reporting Functions

Functions for saving results and generating reports.
"""

def save_test_predictions(results: List[Dict[str, Any]], output_file: Path, logger: logging.Logger):
    """
    Save test predictions in the original format with prediction field added.

    Args:
        results: List of results with predictions
        output_file: Path to save the output JSON
        logger: Logger instance
    """
    output_data = []

    for result in results:
        # Start with original data if available
        if "original_data" in result:
            item = result["original_data"].copy()
        else:
            item = {
                "claim": result["claim"],
                "claim_id": result["claim_id"],
                "claim_date": result.get("claim_date", ""),
                "speaker": result.get("speaker", None),
                "original_claim_url": result.get("original_claim_url", None),
                "reporting_source": result.get("reporting_source", None),
                "location_ISO_code": result.get("location_ISO_code", None)
            }

        # Add prediction field
        item["prediction"] = result.get("prediction", None)
        if result.get("prediction_error"):
            item["prediction_error"] = result["prediction_error"]

        output_data.append(item)

    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(output_data, f, indent=4, ensure_ascii=False)

    logger.info(f"Test predictions saved to {output_file}")
    print(f"✓ Test predictions saved to {output_file}")


def save_results_with_metrics(results: List[Dict[str, Any]], metrics: Dict[str, Any],
                               output_dir: Path, split_name: str, logger: logging.Logger):
    """
    Save results and metrics for labeled data.

    Args:
        results: List of results with predictions
        metrics: Calculated metrics
        output_dir: Directory to save outputs
        split_name: Name of the data split (e.g., 'seen', 'unseen', 'all')
        logger: Logger instance
    """
    # Save predictions as CSV
    predictions_file = output_dir / f"{split_name}_predictions.csv"
    df_results = pd.DataFrame(results)
    df_results.to_csv(predictions_file, index=False, encoding='utf-8')
    logger.info(f"Predictions saved to {predictions_file}")

    # Save predictions as JSON
    predictions_json = output_dir / f"{split_name}_predictions.json"
    with open(predictions_json, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=4, ensure_ascii=False)
    logger.info(f"Predictions (JSON) saved to {predictions_json}")

    # Save metrics
    metrics_file = output_dir / f"{split_name}_metrics.json"
    with open(metrics_file, 'w', encoding='utf-8') as f:
        json.dump(metrics, f, indent=4)
    logger.info(f"Metrics saved to {metrics_file}")

    print(f"✓ {split_name.capitalize()} results saved to {output_dir}")


def generate_summary_report(seen_metrics: Dict, unseen_metrics: Dict,
                            comparison: Dict, output_dir: Path, logger: logging.Logger):
    """
    Generate a comprehensive summary report.

    Args:
        seen_metrics: Metrics for seen data
        unseen_metrics: Metrics for unseen data
        comparison: Comparison statistics
        output_dir: Directory to save the report
        logger: Logger instance
    """
    summary = {
        "experiment_info": {
            "dataset": DATASET_NAME,
            "model": MODEL_NAME,
            "temporal_split_date": TEMPORAL_SPLIT_DATE,
            "canonical_labels": CANONICAL_LABELS,
            "balanced_sampling": BALANCED_SAMPLING,
            "sampling_seed": SAMPLING_SEED if BALANCED_SAMPLING else None,
            "timestamp": datetime.now().isoformat()
        },
        "seen_data": seen_metrics,
        "unseen_data": unseen_metrics,
        "comparison": comparison
    }

    # Add sampling info if present in comparison
    if "sampling_info" in comparison:
        summary["experiment_info"]["sampling_info"] = comparison["sampling_info"]

    summary_file = output_dir / "summary.json"
    with open(summary_file, 'w', encoding='utf-8') as f:
        json.dump(summary, f, indent=4)

    logger.info(f"Summary report saved to {summary_file}")
    print(f"✓ Summary report saved to {summary_file}")

    # Print summary to console
    print("\n" + "=" * 80)
    print("EXPERIMENT SUMMARY")
    print("=" * 80)
    print(f"Dataset: {DATASET_NAME}")
    print(f"Model: {MODEL_NAME}")
    print(f"Temporal Split: {TEMPORAL_SPLIT_DATE}")

    # Show sampling info if enabled
    if comparison.get("sampling_info", {}).get("enabled"):
        si = comparison["sampling_info"]
        print(f"\nBALANCED SAMPLING:")
        print(f"  Seed: {si['seed']}")
        print(f"  Original Seen: {si['original_seen_count']} -> Sampled: {si['sampled_seen_count']}")

    print("\nSEEN DATA PERFORMANCE:")
    acc = seen_metrics.get('accuracy', 'N/A')
    print(f"  Accuracy: {acc if acc == 'N/A' else f'{acc:.4f}'}")
    f1 = seen_metrics.get('macro_f1', 'N/A')
    print(f"  Macro F1: {f1 if f1 == 'N/A' else f'{f1:.4f}'}")
    print(f"  Samples: {seen_metrics.get('total_samples', 'N/A')}")
    print("\nUNSEEN DATA PERFORMANCE:")
    acc = unseen_metrics.get('accuracy', 'N/A')
    print(f"  Accuracy: {acc if acc == 'N/A' else f'{acc:.4f}'}")
    f1 = unseen_metrics.get('macro_f1', 'N/A')
    print(f"  Macro F1: {f1 if f1 == 'N/A' else f'{f1:.4f}'}")
    print(f"  Samples: {unseen_metrics.get('total_samples', 'N/A')}")

    if isinstance(comparison.get("statistical_tests"), dict):
        print("\nSTATISTICAL SIGNIFICANCE:")
        print(f"  Accuracy Difference: {comparison['accuracy_difference']:.4f}")
        print(f"  T-test p-value: {comparison['statistical_tests']['t_test']['p_value']:.4f}")
        print(f"  Chi-square p-value: {comparison['statistical_tests']['chi_square_test']['p_value']:.4f}")
        print(f"  Interpretation: {comparison['statistical_tests']['t_test']['interpretation']}")
    print("=" * 80)

print("✓ Output functions defined")

"""## 8. Main Execution Pipeline

Run the complete inference and evaluation pipeline.
"""

# Setup logger
log_file = OUTPUT_DIR / "main_run_log.txt"
logger = setup_logger(log_file)

logger.info("=" * 80)
logger.info("STARTING FACT-CHECK INFERENCE PIPELINE")
logger.info("=" * 80)
logger.info(f"Dataset: {DATASET_NAME}")
logger.info(f"Model: {MODEL_NAME}")
logger.info(f"Output Directory: {OUTPUT_DIR}")
logger.info(f"Canonical Labels: {CANONICAL_LABELS}")
logger.info(f"Temporal Split Date: {TEMPORAL_SPLIT_DATE}")

print(f"\n{'=' * 80}")
print(f"Starting inference pipeline for {DATASET_NAME}")
print(f"{'=' * 80}\n")

# Load dataset
claims, is_test = load_dataset_by_name(DATASET_NAME)
logger.info(f"Loaded {len(claims)} claims (is_test={is_test})")

# Branch based on test vs labeled data
if is_test:
    # ==================== TEST DATA PIPELINE ====================
    logger.info("Processing TEST data (no labels available)")

    # Process all claims
    results = process_claims(claims, is_test=True, logger=logger)

    # Save predictions in original format with prediction field
    output_file = OUTPUT_DIR / "predictions_with_labels.json"
    save_test_predictions(results, output_file, logger)

    # Generate test summary
    successful_predictions = sum(1 for r in results if r.get("prediction"))
    failed_predictions = len(results) - successful_predictions

    test_summary = {
        "dataset": DATASET_NAME,
        "model": MODEL_NAME,
        "total_claims": len(results),
        "successful_predictions": successful_predictions,
        "failed_predictions": failed_predictions,
        "success_rate": round(successful_predictions / len(results), 4) if results else 0,
        "timestamp": datetime.now().isoformat()
    }

    summary_file = OUTPUT_DIR / "test_summary.json"
    with open(summary_file, 'w', encoding='utf-8') as f:
        json.dump(test_summary, f, indent=4)

    print("\n" + "=" * 80)
    print("TEST DATA SUMMARY")
    print("=" * 80)
    print(f"Total Claims: {test_summary['total_claims']}")
    print(f"Successful Predictions: {test_summary['successful_predictions']}")
    print(f"Failed Predictions: {test_summary['failed_predictions']}")
    print(f"Success Rate: {test_summary['success_rate']:.4f}")
    print("=" * 80)

    logger.info("Test data processing complete")

else:
    # ==================== LABELED DATA PIPELINE ====================
    logger.info("Processing LABELED data with temporal split analysis")

    # Split data by date
    seen_claims, unseen_claims = split_by_date(claims, TEMPORAL_SPLIT_DATE)

    # Apply balanced sampling if enabled
    sampling_info = None
    if BALANCED_SAMPLING and len(seen_claims) > len(unseen_claims):
        original_seen_count = len(seen_claims)
        target_size = len(unseen_claims)

        # Set random seed for reproducibility
        random.seed(SAMPLING_SEED)

        # Sample seen claims to match unseen size
        sampled_seen_claims = random.sample(seen_claims, target_size)

        # Save sampling information
        sampling_info = {
            "enabled": True,
            "seed": SAMPLING_SEED,
            "original_seen_count": original_seen_count,
            "sampled_seen_count": target_size,
            "unseen_count": len(unseen_claims),
            "sampled_claim_ids": [c.get("claim_id") for c in sampled_seen_claims],
            "timestamp": datetime.now().isoformat()
        }

        # Save sampling info to file
        sampling_file = OUTPUT_DIR / "sampling_info.json"
        with open(sampling_file, 'w', encoding='utf-8') as f:
            json.dump(sampling_info, f, indent=4)

        print(f"\n📊 BALANCED SAMPLING ENABLED:")
        print(f"   Original seen claims: {original_seen_count}")
        print(f"   Sampled seen claims: {target_size}")
        print(f"   Unseen claims: {len(unseen_claims)}")
        print(f"   Sampling seed: {SAMPLING_SEED}")
        print(f"   Sampling info saved to: {sampling_file}\n")

        logger.info(f"Balanced sampling enabled: {original_seen_count} -> {target_size} seen claims (seed={SAMPLING_SEED})")

        seen_claims = sampled_seen_claims
    else:
        sampling_info = {"enabled": False}
        if BALANCED_SAMPLING:
            print(f"\n⚠ Balanced sampling requested but seen ({len(seen_claims)}) <= unseen ({len(unseen_claims)}). Processing all.\n")

    # Create subdirectories for seen/unseen
    seen_dir = OUTPUT_DIR / "seen"
    unseen_dir = OUTPUT_DIR / "unseen"
    seen_dir.mkdir(exist_ok=True)
    unseen_dir.mkdir(exist_ok=True)

    # Process seen data
    logger.info("=" * 80)
    logger.info("PROCESSING SEEN DATA (before temporal split)")
    logger.info("=" * 80)
    seen_logger = setup_logger(seen_dir / "seen_run_log.txt")
    seen_results = process_claims(seen_claims, is_test=False, logger=seen_logger)
    seen_metrics = calculate_metrics(seen_results, seen_logger)
    save_results_with_metrics(seen_results, seen_metrics, seen_dir, "seen", seen_logger)

    # Process unseen data
    logger.info("=" * 80)
    logger.info("PROCESSING UNSEEN DATA (after temporal split)")
    logger.info("=" * 80)
    unseen_logger = setup_logger(unseen_dir / "unseen_run_log.txt")
    unseen_results = process_claims(unseen_claims, is_test=False, logger=unseen_logger)
    unseen_metrics = calculate_metrics(unseen_results, unseen_logger)
    save_results_with_metrics(unseen_results, unseen_metrics, unseen_dir, "unseen", unseen_logger)

    # Compare seen vs unseen
    comparison = compare_seen_unseen(seen_results, unseen_results, logger)

    # Add sampling info to comparison if applicable
    if sampling_info:
        comparison["sampling_info"] = sampling_info

    # Generate comprehensive summary report
    generate_summary_report(seen_metrics, unseen_metrics, comparison, OUTPUT_DIR, logger)

    logger.info("Labeled data processing complete")

logger.info("=" * 80)
logger.info("PIPELINE COMPLETE")
logger.info("=" * 80)

print(f"\n✓ All outputs saved to: {OUTPUT_DIR}")
print(f"✓ Log file: {log_file}")

"""## 9. Quick Configuration Examples

Examples for different dataset configurations. Uncomment and modify the configuration section (Section 2) to use these.

### Example 1: FACTors Dataset
```python
DATASET_NAME = "factors"
CANONICAL_LABELS = ["True", "False", "Misleading", "Mixture"]
TEMPORAL_SPLIT_DATE = "2024-01-01"
```

### Example 2: FACTors with Balanced Sampling
```python
DATASET_NAME = "factors"
CANONICAL_LABELS = ["True", "False", "Misleading", "Mixture"]
TEMPORAL_SPLIT_DATE = "2024-01-01"
BALANCED_SAMPLING = True  # Sample seen data to match unseen size
SAMPLING_SEED = 42  # Change seed for different samples (e.g., 123, 456, 789)
```

### Example 3: FEVER Train with Custom Labels
```python
DATASET_NAME = "fever_train"
CANONICAL_LABELS = ["Supported", "Refuted", "Misleading", "Partially true"]
TEMPORAL_SPLIT_DATE = "2021-01-01"
```

### Example 4: FEVER Test Data (No Labels)
```python
DATASET_NAME = "fever_test_2023_2024"
# Labels not needed for test data
```

### Example 5: ClaimReview Plus
```python
DATASET_NAME = "claimreview_plus"
CANONICAL_LABELS = ["True", "False", "Misleading", "Mixture"]
TEMPORAL_SPLIT_DATE = "2023-01-01"
MAX_SAMPLES = 1000  # Process only first 1000 samples
```

### Example 6: Different Model
```python
MODEL_NAME = "gpt-4o-mini"  # or any other available model
AVALAI_API_KEY = "your-api-key-here"
```

---

## Notes

- **Rate Limiting**: If you encounter 429 errors, increase `SLEEP_BETWEEN_CALLS` (e.g., to 2.0 or 3.0 seconds)
- **Sampling**: Set `MAX_SAMPLES` to limit processing for testing purposes
- **Balanced Sampling**: For large datasets like FACTors, set `BALANCED_SAMPLING = True` to sample seen data to match unseen data size. Use different `SAMPLING_SEED` values for multiple runs with different samples.
- **Labels**: Always ensure `CANONICAL_LABELS` matches your dataset's label scheme
- **Temporal Split**: Adjust `TEMPORAL_SPLIT_DATE` based on your research question
- **Test Data**: For test datasets, predictions are saved in the original format + prediction field
"""